version: "2.1"
services:
  intra:
    container_name: intra
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - intradb:intradb
    # restart: always
  intradb:
    container_name: intradb
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root # use dockerenv
    volumes:
      - /tmp/db:/var/lib/mysql
      - ./migrations:/config/migrations
    ports:
      - 3306:3306